import { StyleSheet } from 'react-native';
import { createStyles } from 'shared/theme/createStyles';

export const useStyles = createStyles(({ theme, scale }: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.palette.cream,
    },
    contentContainer: {
      marginHorizontal: scale(16),
    },
    dragButtonContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: scale(8),
    },
    dragButton: {
      height: scale(5),
      width: scale(42),
      borderRadius: scale(3),
      backgroundColor: theme.palette.gray,
    },
    header: {
      marginTop: scale(14),
      color: theme.palette.textDefault,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    closeButton: {
      height: scale(38),
      width: scale(38),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: scale(12),
      backgroundColor: theme.palette.backgroundGreen,
    },
    title: {
      fontSize: scale(20),
      fontWeight: '700',
      color: theme.palette.text,
    },
    label: {
      fontSize: scale(13),
      fontWeight: '600',
      color: theme.palette.inputText,
      marginBottom: scale(8),
    },
    input: {
      height: scale(52),
      borderRadius: scale(14),
      backgroundColor: theme.palette.white,
      borderWidth: scale(1),
      borderColor: theme.palette.inputBorder,
      paddingHorizontal: scale(15),
      color: theme.palette.text,
    },
    descriptionInput: {
      minHeight: scale(120),
      paddingTop: scale(16),
      textAlignVertical: 'top',
    },
    section: {
      marginTop: scale(20),
    },
    sectionMap: {
      marginTop: scale(20),
    },
    mapContainer: {
      height: scale(140),
      width: '100%',
      borderRadius: scale(16),
      overflow: 'hidden',
    },
    map: {
      height: scale(140),
      width: '100%',
      borderRadius: scale(16),
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      height: scale(60),
      backgroundColor: theme.palette.white,
      borderWidth: scale(1),
      borderRadius: scale(14),
      borderColor: theme.palette.inputBorder,
    },
    starsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: scale(15),
    },
    starButton: {
      marginRight: scale(15),
    },
    ratingText: {
      fontSize: scale(16),
      fontWeight: '600',
      marginRight: scale(15),
    },
    commentInput: {
      height: scale(80),
      borderRadius: scale(14),
      backgroundColor: theme.palette.white,
      borderWidth: scale(1),
      borderColor: theme.palette.inputBorder,
      paddingHorizontal: scale(15),
      color: theme.palette.text,
    },
    cardContainer: {
      height: scale(65),
      width: '100%',
      backgroundColor: theme.palette.white,
      borderColor: theme.palette.forest,
      borderWidth: scale(1),
      borderRadius: scale(14),
      marginBottom: scale(8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: scale(10),
    },
    cardText: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    cardIconContainer: {
      height: scale(34),
      width: scale(34),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.palette.backgroundGreen,
      borderRadius: scale(10),
      marginRight: scale(10),
    },
    typeTitle: {
      fontSize: scale(14.5),
      fontWeight: 'bold',
      color: theme.palette.textDefault,
    },
    typeDescription: {
      fontSize: scale(12),
      color: theme.palette.textLight,
    },
    amenityCard: {
      width: '100%',
      height: scale(60),
      backgroundColor: theme.palette.white,
      marginBottom: scale(8),
      borderRadius: scale(14),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    amenityTitle: {
      fontSize: scale(14.5),
      color: theme.palette.textDefault,
    },
    footerContainer: {
      height: scale(60),
      paddingHorizontal: scale(15),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: scale(20),
      borderColor: '#1F2A1D12',
      borderTopWidth: scale(1),
    },
    cancelButton: {
      height: scale(54),
      width: scale(132),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.palette.buttonCancel,
      borderRadius: scale(16),
    },
    cancelText: {
      color: theme.palette.inputText,
    },
    publishButton: {
      height: scale(54),
      width: scale(184),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.palette.forest,
      borderRadius: scale(16),
    },
    publishText: {
      fontSize: scale(16),
      fontWeight: 'bold',
      color: theme.palette.white,
      marginLeft: scale(10),
    },
    centerPin: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      marginLeft: -18,
      marginTop: -36,
    },
    loader: {
      height: scale(65),
      width: scale(65),
      top: scale(3)
    },
  }),
);
