export interface IAppTheme {
  palette: {
    none: `none`;
    dark: `#${string}`;
    textGreen: `#${string}`;
    textDefault: `#${string}`;
    blue: `#${string}`;
    blueSecondary: `#${string}`;
    primary: `#${string}`;
    gray: `#${string}`;
    disabled: `#${string}`;
    secondary: `#${string}`;
    white: `#${string}`;
    primaryGray: `#${string}`;
    secondaryDisabled: `#${string}`;
    accent: `#${string}`;
    accentHover: `#${string}`;
    accentPressed: `#${string}`;
    accentDisabled: `#${string}`;
    danger: `#${string}`;
    dangerLight: `#${string}`;
    dangerHover: `#${string}`;
    dangerDisabled: `#${string}`;
    orange: `#${string}`;
    accentDisabled1: `#${string}`;
    secondaryWhite: `#${string}`;
    grayPrimary: `#${string}`;
    grayLight: `#${string}`;
    success: `#${string}`;
    greenLight: `#${string}`;
    successLight: `#${string}`;
    disabledButton: `#${string}`;
    blueDark: `#${string}`;
    secondaryGray: `#${string}`;
    grayPrimary1: `#${string}`;
    black70: `#${string}`;
    black40: `#${string}`;
    neutralBackground: `#${string}`;
    textBlack: `#${string}`;
    black50: `#${string}`;
    main20: `#${string}`;
    black80: `#${string}`;
    main10: `#${string}`;
    blueBorder: `#${string}`;
    greenBorder: `#${string}`;
    redBackground: `#${string}`;
    white1: `#${string}`;
    greenBackground: `#${string}`;
    red1: `#${string}`;
    red2: `#${string}`;
    yellowBorder: `#${string}`;
    blueLight: `#${string}`;
    blueLightBackground: `#${string}`;
    blueLogo: `#${string}`;
    whiteBackground: `#${string}`;
    greenLightBackground: `#${string}`;
    greenLightBorder: `#${string}`;
  };
}

export const defaultTheme: IAppTheme = {
  palette: {
    none: 'none',
    primary: '#000000',
    textBlack: '#141415',
    dark: '#242424',
    textGreen: '#142F32',
    textDefault: '#1D3252',
    blueBorder: '#234D65',
    blueSecondary: '#4A87CE',
    blue: '#3C8AE6',
    blueDark: '#2778D8',
    blueLogo: '#95C6FF',
    blueLightBackground: '#C9E2FF',
    blueLight: '#ECF5FF',
    primaryGray: '#66727F',
    grayPrimary: '#6A6A6A',
    grayPrimary1: '#757575',
    black80: '#444447',
    black70: '#616161',
    black50: '#8F8C8C',
    main10: '#F1F5FA',
    gray: '#8C8A8A',
    black40: '#9C9C9C',
    disabled: '#AAA8A8',
    grayLight: '#B8B8B8',
    secondaryDisabled: '#E6E6E6',
    white1: '#EDEDED',
    secondaryWhite: '#FCFCFF',
    secondary: '#F2F4F7',
    neutralBackground: '#F6F6F7',
    secondaryGray: '#DCDEE0',
    white: '#FFFFFF',
    dangerLight: '#F9F9F9',
    whiteBackground: '#f4f4f5',
    accentDisabled: '#FFEAE1',
    dangerDisabled: '#FAD6D6',
    accentDisabled1: '#FFDBCB',
    accentHover: '#FFB190',
    yellowBorder: '#F4B102',
    accent: '#E9713E',
    orange: '#F28354',
    accentPressed: '#FF6A2A',
    redBackground: '#FF5E5E',
    red1: '#EF2428',
    red2: '#FF3D00',
    danger: '#E73430',
    dangerHover: '#D22626',
    greenLight: '#82CCB3',
    greenLightBackground: '#F0FFF4',
    greenLightBorder: '#00CC2D',
    disabledButton: '#4DA781',
    greenBackground: '#61C388',
    success: '#0CB653',
    greenBorder: '#0D464D',
    successLight: '#DBF1D9',
    main20: '#D6E7FA',
  },
};
