export const APP_ICONS = Object.freeze({
    'search': require('shared/assets/icons/search.png'),
    'filter': require('shared/assets/icons/filter.png'),
    'tent': require('shared/assets/icons/tent.png'),
    'hammock': require('shared/assets/icons/hammock.png'),
    'truck': require('shared/assets/icons/truck.png'),
    'close': require('shared/assets/icons/close.png'),
    'star_filled': require('shared/assets/icons/star_filled.png'),
    'star_outline': require('shared/assets/icons/star_outline.png'),
    'checkBox': require('shared/assets/icons/checkBox.png'),
    'checkBoxUnchecked': require('shared/assets/icons/checkBoxUnchecked.png'),
    'campfire': require('shared/assets/icons/campfire.png'),
    'firewood': require('shared/assets/icons/firewood.png'),
    'forest': require('shared/assets/icons/forest.png'),
    'gazebo': require('shared/assets/icons/gazebo.png'),
    'lake': require('shared/assets/icons/lake.png'),
    'parking': require('shared/assets/icons/parking.png'),
    'shade': require('shared/assets/icons/shade.png'),
    'signal': require('shared/assets/icons/signal.png'),
    'toilet-paper': require('shared/assets/icons/toilet-paper.png'),
    'trash': require('shared/assets/icons/trash.png'),
    'water': require('shared/assets/icons/water.png'),
    'check': require('shared/assets/icons/check.png'),
    'pin': require('shared/assets/icons/pin.png'),
    'help': require('shared/assets/icons/help.png'),
    'camping': require('shared/assets/icons/camping.png'),
    'camera': require('shared/assets/icons/camera.png'),
});
